using System;
using Microsoft.EntityFrameworkCore.Migrations;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CortexiaAuth.Api.Migrations
{
    /// <inheritdoc />
    public partial class AddGeoDataTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterDatabase()
                .Annotation("Npgsql:PostgresExtension:postgis", ",,");

            // EdgeCciMeasurements et EdgeSnapshots sont partitionnées par mois sur MeasuredAt (fort volume
            // attendu, append-only) : EF Core ne sait pas déclarer "PARTITION BY", on passe donc par du SQL
            // brut. Une partition DEFAULT capte tout intervalle non encore créé par le service d'import.
            migrationBuilder.Sql(
                """
                CREATE TABLE "EdgeCciMeasurements" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
                    "MeasuredAt" timestamp with time zone NOT NULL,
                    "EdgeU" bigint NOT NULL,
                    "EdgeV" bigint NOT NULL,
                    "EdgeKey" smallint NOT NULL,
                    "PostedAt" timestamp with time zone NOT NULL,
                    "Direction" real NOT NULL,
                    "Cci" real NULL,
                    "CciCustom" real NULL,
                    "HasMeasure" boolean NOT NULL,
                    "SuitcaseIds" text[] NOT NULL,
                    "RateLeaves" real NULL,
                    "RateCigarettes" real NULL,
                    "RateGums" real NULL,
                    "RatePapers" real NULL,
                    "RateGrits" real NULL,
                    "RateBottles" real NULL,
                    "RateExcrements" real NULL,
                    "RateGlassDebris" real NULL,
                    "RateSyringues" real NULL,
                    "CustomCciPerTypesJson" jsonb NOT NULL,
                    CONSTRAINT "PK_EdgeCciMeasurements" PRIMARY KEY ("Id", "MeasuredAt")
                ) PARTITION BY RANGE ("MeasuredAt");

                CREATE TABLE "EdgeCciMeasurements_default" PARTITION OF "EdgeCciMeasurements" DEFAULT;
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE "EdgeSnapshots" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
                    "MeasuredAt" timestamp with time zone NOT NULL,
                    "EdgeU" bigint NOT NULL,
                    "EdgeV" bigint NOT NULL,
                    "EdgeKey" smallint NOT NULL,
                    "Direction" real NOT NULL,
                    "SpeedMs" real NOT NULL,
                    "SuitcaseId" text NOT NULL,
                    "Location" geography(Point,4326) NOT NULL,
                    "Details" smallint[] NOT NULL,
                    "PostedAt" timestamp with time zone NOT NULL,
                    "CityId" integer NOT NULL,
                    CONSTRAINT "PK_EdgeSnapshots" PRIMARY KEY ("Id", "MeasuredAt")
                ) PARTITION BY RANGE ("MeasuredAt");

                CREATE TABLE "EdgeSnapshots_default" PARTITION OF "EdgeSnapshots" DEFAULT;
                """);

            migrationBuilder.CreateTable(
                name: "RoadEdges",
                columns: table => new
                {
                    U = table.Column<long>(type: "bigint", nullable: false),
                    V = table.Column<long>(type: "bigint", nullable: false),
                    Key = table.Column<short>(type: "smallint", nullable: false),
                    OsmIds = table.Column<long[]>(type: "bigint[]", nullable: false),
                    Highway = table.Column<string>(type: "text", nullable: true),
                    Name = table.Column<string>(type: "text", nullable: true),
                    LengthMeters = table.Column<double>(type: "double precision", nullable: false),
                    Geometry = table.Column<Geometry>(type: "geometry", nullable: false),
                    PropertiesJson = table.Column<string>(type: "jsonb", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RoadEdges", x => new { x.U, x.V, x.Key });
                });

            migrationBuilder.CreateIndex(
                name: "IX_EdgeCciMeasurements_EdgeU_EdgeV_EdgeKey_MeasuredAt",
                table: "EdgeCciMeasurements",
                columns: new[] { "EdgeU", "EdgeV", "EdgeKey", "MeasuredAt" });

            migrationBuilder.CreateIndex(
                name: "IX_EdgeCciMeasurements_MeasuredAt",
                table: "EdgeCciMeasurements",
                column: "MeasuredAt")
                .Annotation("Npgsql:IndexMethod", "BRIN");

            migrationBuilder.CreateIndex(
                name: "IX_EdgeSnapshots_CityId",
                table: "EdgeSnapshots",
                column: "CityId");

            migrationBuilder.CreateIndex(
                name: "IX_EdgeSnapshots_EdgeU_EdgeV_EdgeKey_MeasuredAt",
                table: "EdgeSnapshots",
                columns: new[] { "EdgeU", "EdgeV", "EdgeKey", "MeasuredAt" });

            migrationBuilder.CreateIndex(
                name: "IX_EdgeSnapshots_Location",
                table: "EdgeSnapshots",
                column: "Location")
                .Annotation("Npgsql:IndexMethod", "GIST");

            migrationBuilder.CreateIndex(
                name: "IX_EdgeSnapshots_MeasuredAt",
                table: "EdgeSnapshots",
                column: "MeasuredAt")
                .Annotation("Npgsql:IndexMethod", "BRIN");

            migrationBuilder.CreateIndex(
                name: "IX_RoadEdges_Geometry",
                table: "RoadEdges",
                column: "Geometry")
                .Annotation("Npgsql:IndexMethod", "GIST");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "EdgeCciMeasurements");

            migrationBuilder.DropTable(
                name: "EdgeSnapshots");

            migrationBuilder.DropTable(
                name: "RoadEdges");

            migrationBuilder.AlterDatabase()
                .OldAnnotation("Npgsql:PostgresExtension:postgis", ",,");
        }
    }
}
