// <auto-generated />
using System;
using CortexiaAuth.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CortexiaAuth.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810141335_AddAppUsers")]
    partial class AddAppUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CortexiaAuth.Api.Models.AccessTokenRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AccessTokens");
                });

            modelBuilder.Entity("CortexiaAuth.Api.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CortexiaPasswordProtected")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CortexiaUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("CortexiaAuth.Api.Models.EdgeCciMeasurement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("Cci")
                        .HasColumnType("real");

                    b.Property<float?>("CciCustom")
                        .HasColumnType("real");

                    b.Property<string>("CustomCciPerTypesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<float>("Direction")
                        .HasColumnType("real");

                    b.Property<short?>("EdgeKey")
                        .HasColumnType("smallint");

                    b.Property<long?>("EdgeU")
                        .HasColumnType("bigint");

                    b.Property<long?>("EdgeV")
                        .HasColumnType("bigint");

                    b.Property<bool>("HasMeasure")
                        .HasColumnType("boolean");

                    b.Property<string>("PlaceId")
                        .HasColumnType("text");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("RateBottles")
                        .HasColumnType("real");

                    b.Property<float?>("RateCigarettes")
                        .HasColumnType("real");

                    b.Property<float?>("RateExcrements")
                        .HasColumnType("real");

                    b.Property<float?>("RateGlassDebris")
                        .HasColumnType("real");

                    b.Property<float?>("RateGrits")
                        .HasColumnType("real");

                    b.Property<float?>("RateGums")
                        .HasColumnType("real");

                    b.Property<float?>("RateLeaves")
                        .HasColumnType("real");

                    b.Property<float?>("RatePapers")
                        .HasColumnType("real");

                    b.Property<float?>("RateSyringues")
                        .HasColumnType("real");

                    b.PrimitiveCollection<string[]>("SuitcaseIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id", "MeasuredAt");

                    b.HasIndex("MeasuredAt");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("MeasuredAt"), "BRIN");

                    b.HasIndex("PlaceId", "MeasuredAt")
                        .HasFilter("\"PlaceId\" IS NOT NULL");

                    b.HasIndex("EdgeU", "EdgeV", "EdgeKey", "MeasuredAt");

                    b.ToTable("EdgeCciMeasurements");
                });

            modelBuilder.Entity("CortexiaAuth.Api.Models.EdgeSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<short[]>("Details")
                        .IsRequired()
                        .HasColumnType("smallint[]");

                    b.Property<float>("Direction")
                        .HasColumnType("real");

                    b.Property<short?>("EdgeKey")
                        .HasColumnType("smallint");

                    b.Property<long?>("EdgeU")
                        .HasColumnType("bigint");

                    b.Property<long?>("EdgeV")
                        .HasColumnType("bigint");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography(Point,4326)");

                    b.Property<string>("PlaceId")
                        .HasColumnType("text");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("SpeedMs")
                        .HasColumnType("real");

                    b.Property<string>("SuitcaseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id", "MeasuredAt");

                    b.HasIndex("CityId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("MeasuredAt");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("MeasuredAt"), "BRIN");

                    b.HasIndex("PlaceId", "MeasuredAt")
                        .HasFilter("\"PlaceId\" IS NOT NULL");

                    b.HasIndex("EdgeU", "EdgeV", "EdgeKey", "MeasuredAt");

                    b.ToTable("EdgeSnapshots");
                });

            modelBuilder.Entity("CortexiaAuth.Api.Models.Place", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "GIST");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("CortexiaAuth.Api.Models.RoadEdge", b =>
                {
                    b.Property<long>("U")
                        .HasColumnType("bigint");

                    b.Property<long>("V")
                        .HasColumnType("bigint");

                    b.Property<short>("Key")
                        .HasColumnType("smallint");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<string>("Highway")
                        .HasColumnType("text");

                    b.Property<double>("LengthMeters")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.PrimitiveCollection<long[]>("OsmIds")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.Property<string>("PropertiesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("U", "V", "Key");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "GIST");

                    b.ToTable("RoadEdges");
                });
#pragma warning restore 612, 618
        }
    }
}
